name: Publish DevContainers
run-name: ${{ github.actor }} is publishing the devcontainers 🚀
on:
    workflow_dispatch:
        inputs:
            image-name:
                description: 'Image name'
                required: true
                default: 'its-a-rag'
            tag:
                description: 'Tag'
                required: true
                default: 'dev'
            dockerhub-username:
                description: 'Docker Hub username'
                required: true
                default: '...'
            dockerhub-token:
                description: 'Docker Hub token'
                required: true
                default: '...'
            workspace-folder:
                description: 'Workspace folder'
                required: true
                default: '...'
jobs:
    builds:
        runs-on: ubuntu-latest
        steps:
            - 
                name: Expose GitHub Runtime
                uses: crazy-max/ghaction-github-runtime@v3
            - 
                name: Set up Docker
                uses: docker/setup-docker-action@v4
                with:
                    daemon-config: |
                        {
                            "features": {
                                "containerd-snapshotter": true
                            }
                        }
            - 
                name: Set up QEMU
                uses: docker/setup-qemu-action@v3
                
            -     
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

            - 
                name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ vars.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            - 
                name: Install @devcontainers/cli
                run: npm install -g @devcontainers/cli

            - 
                name: Build image
                run: |
                    devcontainer build \
                    --workspace-folder '...' \
                    --platform linux/amd64,linux/arm64 \
                    --image-name=<image-name>:<tag1> \
                    --image-name=<image-name>:<tag2> \
                    --output type=docker \
                    --cache-from type=gha \
                    --cache-to type=gha,mode=max
            - 
                name: Publish image
                run: docker push --all-tags '<image-name>'